class elmen():
    IDusername = "user-name"
    IDpassword = "password"
    IDContinue = "continue"
    IDFirtName = "first-name"
    IDLastName = "last-name"
    IDPostalCode = "postal-code"
    IDFinish = "finish"
    IDadd ="add-to-cart-sauce-labs-backpack"
    IDremove ="remove-sauce-labs-backpack"
    IDProductImage = "item_4_img_link"
    IDContinueShopping = "continue-shopping"
    IDBurgerMenu = "react-burger-menu-btn"
    IDLogout = "logout_sidebar_link"
    btn_login = "login-button"
    btn_Checkout = "checkout"
    title = "title"
    xPathInvalid = "//div[@id='login_button_container']//form//h3"
    xPathCart = "/html//div[@id='shopping_cart_container']"
    xPathDesc = "//div[@id='cart_contents_container']//div[@class='cart_list']/div[@class='cart_desc_label']"
    xPathImageProduct = "//div[@id='inventory_item_container']//div[@class='inventory_details_container']//div[@class='inventory_details_name large_size']"
    xPathSelect = "//div[@id='header_container']/div[@class='header_secondary_container']//select[@class='product_sort_container']"
    xPathCencel = "/html//button[@id='cancel']"
    CSSNameRequired = ".error-message-container.error"
    
class validasi():
    product = "Products"
    remove = "Remove"
    AddProduct = "Add to cart"
    Descripsi = "Description"
    InvalidUserandPassword = "Epic sadface: Username and password do not match any user in this service"
    BlankUsername = "Epic sadface: Username is required"
    BlankPassword = "Epic sadface: Password is required"
    nameProduct = "Sauce Labs Backpack"
    FNemeRequired = "Error: First Name is required"
    LNameRequired = "Error: Last Name is required"
    PostalRequire = "Error: Postal Code is required"
    URLLogin = "https://www.saucedemo.com/inventory.html"
    URLCart = "https://www.saucedemo.com/cart.html"
    URLInformation = "https://www.saucedemo.com/checkout-step-one.html"
    URLOverview = "https://www.saucedemo.com/checkout-step-two.html"
    URLComplit = "https://www.saucedemo.com/checkout-complete.html"

class Url():
    base_url = "https://www.saucedemo.com/"